version: '3.3'
services:
    redis:
      image: "redis:alpine"
      hostname: redis
      ports:
        - "6379:6379"
    matrix_app:
      image: matrix
      container_name: app
      ports:
        - 3001:3001
      depends_on:
        - redis
